export const data = [
    {
        id: "1",
        product: {
            name: "Gaming Console",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "01 Jan 2024",
        time: "1h 30m",
        value: "$400.00",
        commission: "$120",
    },
    {
        id: "2",
        product: {
            name: "Smartphone",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "05 Feb 2024",
        time: "2h 15m",
        value: "$600.00",
        commission: "$180",
    },
    {
        id: "3",
        product: {
            name: "Laptop Computer",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "10 Mar 2024",
        time: "3h 45m",
        value: "$1,000.00",
        commission: "$300",
    },
    {
        id: "4",
        product: {
            name: "4K Television",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s",
        },
        date: "15 Apr 2024",
        time: "4h 20m",
        value: "$800.00",
        commission: "$240",
    },
    {
        id: "5",
        product: {
            name: "Wireless Headphones",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "20 May 2024",
        time: "5h 10m",
        value: "$200.00",
        commission: "$60",
    },
    {
        id: "6",
        product: {
            name: "Digital Camera",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "25 Jun 2024",
        time: "6h 30m",
        value: "$500.00",
        commission: "$150",
    },
    {
        id: "7",
        product: {
            name: "Smart Watch",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "30 Jul 2024",
        time: "7h 45m",
        value: "$250.00",
        commission: "$75",
    },
    {
        id: "8",
        product: {
            name: "Tablet Device",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s",
        },
        date: "04 Aug 2024",
        time: "8h 20m",
        value: "$450.00",
        commission: "$135",
    },
    {
        id: "9",
        product: {
            name: "Bluetooth Speaker",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "09 Sep 2024",
        time: "9h 10m",
        value: "$180.00",
        commission: "$54",
    },
    {
        id: "10",
        product: {
            name: "Fitness Tracker",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s",
        },
        date: "14 Oct 2024",
        time: "10h 50m",
        value: "$80.00",
        commission: "$24",
    },
    {
        id: "11",
        product: {
            name: "Robot Vacuum Cleaner",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "19 Nov 2024",
        time: "11h 25m",
        value: "$300.00",
        commission: "$90",
    },
    {
        id: "12",
        product: {
            name: "Air Purifier",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "24 Dec 2024",
        time: "12h 15m",
        value: "$220.00",
        commission: "$66",
    },
    {
        id: "13",
        product: {
            name: "Stand Mixer",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "29 Jan 2024",
        time: "13h 05m",
        value: "$350.00",
        commission: "$105",
    },
    {
        id: "14",
        product: {
            name: "Espresso Machine",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "03 Feb 2024",
        time: "14h 50m",
        value: "$400.00",
        commission: "$120",
    },
    {
        id: "15",
        product: {
            name: "Instant Pot",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "08 Mar 2024",
        time: "15h 35m",
        value: "$150.00",
        commission: "$45",
    },
    {
        id: "16",
        product: {
            name: "Smart Thermostat",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s",
        },
        date: "13 Apr 2024",
        time: "16h 20m",
        value: "$200.00",
        commission: "$60",
    },
    {
        id: "17",
        product: {
            name: "E-book Reader",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s",
        },
        date: "18 May 2024",
        time: "17h 05m",
        value: "$120.00",
        commission: "$36",
    },
    {
        id: "18",
        product: {
            name: "Smart Light Bulb",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s",
        },
        date: "23 Jun 2024",
        time: "18h 50m",
        value: "$60.00",
        commission: "$18",
    },
    {
        id: "19",
        product: {
            name: "Electric Toothbrush",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "28 Jul 2024",
        time: "19h 35m",
        value: "$50.00",
        commission: "$15",
    },
    {
        id: "20",
        product: {
            name: "Portable Projector",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "02 Aug 2024",
        time: "20h 45m",
        value: "$500.00",
        commission: "$150",
    },
    {
        id: "21",
        product: {
            name: "Digital Photo Frame",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s",
        },
        date: "07 Sep 2024",
        time: "21h 30m",
        value: "$120.00",
        commission: "$36",
    },
    {
        id: "22",
        product: {
            name: "Drone",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "12 Oct 2024",
        time: "22h 15m",
        value: "$800.00",
        commission: "$240",
    },
    {
        id: "23",
        product: {
            name: "Gaming Chair",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "17 Nov 2024",
        time: "23h 50m",
        value: "$300.00",
        commission: "$90",
    },
    {
        id: "24",
        product: {
            name: "VR Headset",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "22 Dec 2024",
        time: "24h 25m",
        value: "$400.00",
        commission: "$120",
    },
    {
        id: "25",
        product: {
            name: "Smart Home Hub",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "27 Jan 2024",
        time: "25h 15m",
        value: "$150.00",
        commission: "$45",
    },
    {
        id: "26",
        product: {
            name: "Noise-Canceling Headphones",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "02 Feb 2024",
        time: "26h 50m",
        value: "$300.00",
        commission: "$90",
    },
    {
        id: "27",
        product: {
            name: "Action Camera",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "07 Mar 2024",
        time: "27h 35m",
        value: "$250.00",
        commission: "$75",
    },
    {
        id: "28",
        product: {
            name: "Electric Scooter",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s", 
        },
        date: "12 Apr 2024",
        time: "28h 20m",
        value: "$500.00",
        commission: "$150",
    },
    {
        id: "29",
        product: {
            name: "Air Fryer",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s",
        },
        date: "17 May 2024",
        time: "29h 15m",
        value: "$100.00",
        commission: "$30",
    },
    {
        id: "30",
        product: {
            name: "Wireless Mouse",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv2M9UynBeJz8C8SnI3ViVFxqBkXTX03OL8g&s",
        },
        date: "22 Jun 2024",
        time: "30h 50m",
        value: "$40.00",
        commission: "$12",
    },
];